### ISSUE TITLE
Salesperson problem

### ISSUE THREAD

**Issue by JulianoGTZ** [league-of-developers/javascript-exercises#23]
## Context

A salesperson needs a function that calculates the total price due to a customer. 

The algorithm must receive the **product code** and the **quantity** purchased and calculate the total price using the table below.

|Product Code          |Unit Price                           |
|----------------|-------------------------------|
|1001|`5.32`|
|1324    |`6.45`|
|6548 |`2.37`|
|0987 |`5.32`|
|7623|`6.45`|

## TODO
- [ ] Create a branch with the right name 
- [ ] Use the exercise statement as a test description
- [ ] Make unit tests
